### ISSUE TITLE
View the buoy on RViz

### ISSUE THREAD

**Issue by chapulina** [osrf/buoy_sim#25]
- [x] Publish robot description with the help of [sdformat_urdf](https://github.com/ros/sdformat_urdf).
- [x] Publish TF, see [this demo](https://github.com/gazebosim/ros_gz/blob/ros2/ros_ign_gazebo_demos/launch/tf_bridge.launch.py)
- [x] Add RViz and its config as an option to the launch files

**Comment by andermi** [comment]
What I think would be really cool eventually:

- excite a sim buoy with telemetry from the physical buoy
- excite a sim buoy with simulated waves created with the properties measured from the wave spotter buoy
- view both of these in RVIZ along with an additional buoy that moves as best we can approximate from dead reckoning with physical buoy telemetry
