### ISSUE TITLE
Add physical properties to mbari_wec model

### ISSUE THREAD

**Issue by andermi** [osrf/buoy_sim#31]
I've put properties from Fran&ccedil;ois in a spreadsheet. These should be added to the mbari_wec model and/or accounted for in plugins.
[mbari_wec_properties.xlsx](https://github.com/osrf/buoy_sim/files/8626607/mbari_wec_properties.xlsx)

**Comment by quarkytale** [comment]
Thanks for compiling and sharing this!
Making sure if I'm reading the values correctly, the added mass (closed/open) is in z-direction right? Also could you please help me identify the individual terms of Inertia (kg*m^2).

**Comment by chapulina** [comment]
I'm going to work on the Inertia, weight and CoG properties for all links in a standalone PR now. It would help me with #26 so I can work with more realistic dynamics while updating the cable. And it should help your buoyancy efforts too, @quarkytale .

> could you please help me identify the individual terms of Inertia (kg*m^2). I'm assuming its the 3x3 rotational inertia matrix with the format:

I'm going with this same assumption and will verify visually if it looks reasonable.

**Comment by andermi** [comment]
> the added mass (closed/open) is in z-direction

correct!

> 3x3 rotational inertia matrix with the format:

also correct!

**Comment by chapulina** [comment]
Some values we're currently estimating but could need more precise numbers in the future:

- Piston moments of inertia
- Have cone inertia without Trefoil
- Trefoil inertia

**Comment by chapulina** [comment]
For record-keeping, we've moved the CoB of the buoy a bit up to `2.46 m` instead of `2.16 m` in #33 so the box volume matches the shape of the buoy a bit better. We may want to tweak this in the future.
