### ISSUE TITLE
Add wave model

### ISSUE THREAD

**Issue by andermi** [osrf/buoy_sim#49]
We would like to have a physical and visual representation of waves and wave-body interaction. Some implementations can be discussed/tracked here until we choose the appropriate path forward.

1. FFT with OpenGL 3.3
- [Part One](https://www.keithlantz.net/2011/10/ocean-simulation-part-one-using-the-discrete-fourier-transform/)
- [Part Two](https://www.keithlantz.net/2011/11/ocean-simulation-part-two-using-the-fast-fourier-transform/)
- [GitHub](https://github.com/Postrediori/OceanSimulation)

2. With Shaders
- [Gerstner Waves Model](https://app.gazebosim.org/OpenRobotics/fuel/models/Waves)
- [#541 on gz-rendering](https://github.com/gazebosim/gz-rendering/pull/541/)
4. [gz-marine](https://github.com/srmainwaring/asv_wave_sim/tree/gz-marine)
5. Then there's [this](https://community.gazebosim.org/t/simulate-surface-waves-and-marine-vehicle-dynamics/1268/6) :exploding_head:

**Comment by andermi** [comment]
For 1.
Pros:
- Visually appealing
- Very efficient
- Has access to deformable mesh vertices
Cons:
- Doesn't seem to fit with existing Gazebo GLSL program interface like in 2.

**Comment by srmainwaring** [comment]
Hi @andermi, I've started to look into how you might combine the wave rendering and hydrostatics model from [asv_wave_sim](https://github.com/srmainwaring/asv_wave_sim) with the proposed free surface wave-body interaction model being developed in buoy_sim. There's still a lot to resolve but I've made a start getting the environment set up with a couple of test examples and worlds in this branch: 

-https://github.com/srmainwaring/buoy_sim/tree/srmainwaring/gz-sim7-fs_hydro

There are two example wave models available. One is the randomised wave model based on Tessendorf's work, the other is a monochromatic plane wave with period 8s and amplitude 2m. I have also added a test model based on the WEC-Sim ellipsoid used to demonstrate their non-linear hydrostatics approach. This is for eventual benchmarking against their simulation.

I'll add some notes to the branch describing how to get the system set up.

Figure: [mbari_wec_waves.sdf](https://github.com/srmainwaring/buoy_sim/blob/srmainwaring/gz-sim7-fs_hydro-waves/buoy_gazebo/worlds/mbari_wec_waves.sdf) configured to use the [monochromatic_waves]( https://github.com/srmainwaring/buoy_sim/blob/srmainwaring/gz-sim7-fs_hydro-waves/buoy_gazebo/models/monochromatic_waves) model.

![mbari_buoy_monochrome](https://user-images.githubusercontent.com/24916364/189994980-785db451-a472-414a-a8bd-159c393ba9cb.jpg)
