### ISSUE TITLE
 ElectroHydraulicPTO Cleanup

### ISSUE THREAD

**Issue by andermi** [osrf/buoy_sim#62]
@hamilton8415

https://github.com/osrf/buoy_sim/blob/e3a63531572981e2e5c4bd61bc97f0076371acf5/buoy_gazebo/src/ElectroHydraulicPTO/ElectroHydraulicPTO.cpp#L353

Is this supposed to be proportional to x? Wondering if it's stuck at 12.12 from debugging previously

_Originally posted by @andermi in https://github.com/osrf/buoy_sim/issues/57#issuecomment-1152776456_

**Comment by hamilton8415** [comment]
Yes, almost certainly that's a rogue debugging step.  I even have some recall of using a strange number like that.   At the moment, I don't believe the electro-hydraulic PTO implementation is sensitive to piston position.  Outside of higher-order considerations of the hydraulic oil compressibility, the place it would/could be sensitive to position is in simulating the soft-stop features which keep one from driving the ram into the end-stops at full speed.
